kind: pipeline
type: docker
name: default

steps:
- name: make
  image: debian:buster-slim
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    REGISTRY:
      from_secret: docker_registry
    DOCKERVERSION: "19.03.9"
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - apt-get update && apt install -y --no-install-recommends curl make ca-certificates git
  - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-$${DOCKERVERSION}.tgz
  - tar xzvf docker-$${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker
  - rm docker-$${DOCKERVERSION}.tgz
  - sleep 5 # give docker enough time to start
  - echo login $REGISTRY
  - docker login -u $USERNAME -p $PASSWORD $REGISTRY
  - make manifest-list
- name: notify
  image: plugins/matrix
  when:
    status:
    - success
    - failure
  settings:
    homeserver:
      from_secret: matrix-homeserver
    roomid:
      from_secret: matrix-room-id
    userid:
      from_secret: matrix-user-id
    accesstoken:
      from_secret: matrix-access-token

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
